name: "Markdown Table"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Updating readme with markdown table (Jokes, Memes, Quotes)
    runs-on: ubuntu-latest
    steps:
      - uses: lendradxx/markdown-tables@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}